<?php
/**
 * Created by PhpStorm.
 * User: crosstime
 * Date: 2017/10/12
 * Time: 上午11:57
 */

namespace app\admin\controller;


use common\libraries\Common;
use common\server\RoleSearch\RoleSearchServer;


class RoleSearch extends Oauth
{


    public function onConstruct()
    {

        return parent::onConstruct(); // TODO: Change the autogenerated stub
    }


    public function index()
    {

        $account = $this->request->post('account', '' );
        $type = $this->request->post('type/d', 0);

        $page       = $this->request->post('page/d', 1);
        $limit      = $this->request->post('limit/d', 20);
        $platform_id  = $this->request->post('platform_id/d', 1);

//            $product_id  = $this->request->getPost('product_id', 'int', 0);
        $user_name  = $this->request->post('user_name/s',  '');
        $uid  = $this->request->post('uid/d',0);
        $reg_gid  = $this->request->post('reg_gid/s', '');
        $login_gid  = $this->request->post('login_gid/d', 0);
        $server_id  = $this->request->post('server_id/d', 0);
        $role_name  = $this->request->post('role_name/s', '');
        $role_id  = $this->request->post('role_id/d', 0);
        $trans_level = $this->request->post('trans_level/d', 0);
        $role_level = $this->request->post('role_level/d', 0);
        $s_reg_time = $this->request->post('s_reg_time/s', date('Y-m-d',strtotime(date('Y-m-d H:i:s'))-86400));
        $e_reg_time = $this->request->post('e_reg_time/s', date('Y-m-d',strtotime(date('Y-m-d H:i:s'))));
        $s_money = $this->request->post('s_money/d', 0);
        $e_money = $this->request->post('e_money/d', 0);
        $s_reg_days = $this->request->post('s_reg_days/d', 0);
        $e_reg_days = $this->request->post('e_reg_days/d', 0);
        $s_reg_role_days = $this->request->post('s_reg_role_days/d', 0);
        $e_reg_role_days = $this->request->post('e_reg_role_days/d', 0);
        $game_arr = explode(',',$reg_gid);

        $tmp_game_arr = [];
        if($game_arr){
            foreach($game_arr as $k=>$v){
                if(strpos($v,'_')){
                    list($tmp_platform_id,$tmp_game_arr[]) = explode('_',$v);
                }

            }
        }
        $platform_info = Common::getPlatformInfoByPlatformIdAndCache($platform_id);


        $conditions = [
//                'product_id' => $product_id,
            'platform_id' => $platform_info['platform_id'],
            'user_name' => $user_name,
            'uid' => $uid,
            'reg_gid' => $tmp_game_arr,
            'login_gid' => $login_gid,
            'server_id' => $server_id,
            'role_name' => $role_name,
            'role_id' => $role_id,
            'trans_level' => $trans_level,
            'role_level' => $role_level,
            's_reg_time' => strtotime($s_reg_time),
            'e_reg_time' => strtotime($e_reg_time),
            's_money' => $s_money,
            'e_money' => $e_money,
            's_reg_days' => $s_reg_days,
            'e_reg_days' => $e_reg_days,
            's_reg_role_days' => $s_reg_role_days,
            'e_reg_role_days' => $e_reg_role_days,
        ];

        $res = RoleSearchServer::getList($platform_info,$conditions,$page,$limit);

        $count = RoleSearchServer::getCount($platform_info,$conditions);


        $this->rs['code'] = 0;
        $this->rs['msg'] = '获取成功';
        $this->rs['data'] = $res;
        $this->rs['count'] = $count;
        return return_json($this->rs);


    }


}